name: '$(BuildDefinitionName)_$(nextVersion)$(Rev:.r)'

trigger:
- '*'

pool:
  vmImage: 'windows-2019'

variables:
  nextVersion: '1.0'
  buildProjects: '**/*.csproj'
  buildConfiguration: 'Release'
  testProjects: '**/*[Tt]ests/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(buildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(buildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(testProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: push
    publishVstsFeed: '4a29a0d1-45be-4c7a-b1ce-2a38e834f6fb/5473b1dc-c0be-435c-8ebd-a0f86443efee'

- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    ArtifactName: 'drop'
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
